### PR TITLE
Fixed a bug where the dropout event was never emitted

### PR DESCRIPTION
**Pull request by mattsoftware**

### CODE REVIEW

**Comment by tm-rampart** [comment]
Approved by @johnnyman727. [Running tests](https://rampart.tessel.io/jobs/5952).

**Comment by johnnyman727** [comment]
Thanks @mattsoftware!

**Comment by mattsoftware** [comment]
No Problem. More to come if they are welcome :)

**Comment by johnnyman727** [comment]
They are absolutely welcome. :+1:

**Pull request merged**
