### PR TITLE
Swallow exceptions for broken sentences, unless DEBUG=2. Fixes gh-34

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by rwaldron** [comment]
I don't have publish access for this on npm :\

**Comment by johnnyman727** [comment]
@eat-sleep-code I published it for Rick about a week ago.

**Comment by rwaldron** [comment]
Whoops :| sorry I forgot to update here :(

**Comment by eat-sleep-code** [comment]
Cool.   Now my program should run for more than 5 minutes. 👍   I will try it out tomorrow / this weekend.

**Comment by eat-sleep-code** [comment]
I ran `npm update gps-a2235h`

My package.json reflects the following: `"gps-a2235h": "^0.3.1",`

I then tried `t2 run` on my script.   It ran for a while and then boom...

> /tmp/remote-script/node_modules/nmea/nmea.js:1
(function (exports, require, module, __filename, __dirname) { var e,t=require("./codecs/MWV.js"),n=require("./codecs/VTG.js"),r=require("./codecs/DBT.js"),i=require("./codecs/GLL.js"),o=require("./codecs/BWC.js"),s=require("./codecs/GSV.js"),a=require("./codecs/GSA.js"),u=require("./codecs/GGA.js"),c=require("./codecs/RMC.js"),h=require("./codecs/APB.js"),l=require("./codecs/HDT.js"),f=require("./codecs/HDM.js"),d=require("./codecs/RDID.js");module.exports.Helpers=require("./helpers.js"),e=function(e){var t,n=0,r=e.split("*");for(t=1;t<r[0].length;t++)n^=r[0].charCodeAt(t);return n==parseInt(r[1],16)},exports.traditionalDecoders={GGA:u.decode,RMC:c.decode,APB:h.decode,GSA:a.decode,GSV:s.decode,BWC:o.decode,DBT:r.decode,MWV:t.decode,VTG:n.decode,GLL:i.decode,HDT:l.decode,HDM:f.decode,RDID:d.decode},exports.encoders={},exports.encoders[t.TYPE]=t,exports.encoders[n.TYPE]=n,exports.encoders[r.TYPE]=r,exports.encoders[i.TYPE]=i,exports.encoders[l.TYPE]=l,exports.enc

> Error:
 Invalid line:$GPGSA,A,1,
    at Error (native)
    at Object.exports.parse (/tmp/remote-script/node_modules/nmea/nmea.js:1:1287)
    at s.<anonymous> (/tmp/remote-script/node_modules/gps-a2235h/lib/tessel_2/driver.js:1:712)
    at emitOne (events.js:77:13)
    at s.emit (events.js:169:7)
    at null.<anonymous> (/tmp/remote-script/node_modules/gps-a2235h/lib/tessel_2/packetizer.js:1:1103)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Readable.push (_stream_readable.js:111:10)

So this does not appear to be fixed yet.

**Comment by rwaldron** [comment]
I'll take another look. The reality is that we're now patching over failures from another module :(

**Pull request merged**
